[[redirects]]
  from = "/ingest/static/*"
  to = "https://us-assets.i.posthog.com/static/:splat"
  status = 200
  force = true
  headers = { X-From = "netlify" }

[[redirects]]
  from = "/ingest/*"
  to = "https://us.i.posthog.com/:splat"
  status = 200
  force = true
  headers = { X-From = "netlify" }